version: '3'
services:
  liana:
    container_name: liana
    build:
      dockerfile: Dockerfile
      context: .
      tags:
        - liana
    env_file:
      - .env
    ports:
      - 5123:5123
    restart: on-failure
    